### ISSUE TITLE
Questions about usage

### ISSUE THREAD

**Issue by BRTPOB** [peps1/airdcpp-auto-downloader#7]
Hi, I just found this extension and I love it however the usage isn't 100% clear. It's pretty clear, but not totally there. Is there anyway to cache what's already been found, and ignore that in subsequent searches so that errors and warnings aren't constantly popping up?

For example, one of the hubs I'm on I always see these types of errors:
`File lists: The following error(s) occurred when queueing the bundle /downloads/mylar/0-Day Week of 2021.05.03/ from a user DoomBot : Filelist directory not found`

I would love to be able to either block that user, as I've never seen the filelist work, or to have it record that somewhere and stop spamming the message.

Separately, is there anyway to make it so that it has exclusionary terms as well?

As for the warnings, is there anyway for it to recognize that a file or folder exists, add that to some sort of XML or DB and then not search for that in the future? I understand these are huge undertakings if you were willing to do it, but I feel it would help solidify the extension. As it is I love it as it helps make my life easier, even with these minor complaints.

Thanks!

**Comment by peps1** [comment]
sorry, didn't realize there were issues posted.

I haven't seen this error message, unfortunately you can not exclude users from the search, only hubs. So the only thing i could do is record that user and then never queue items if that user is the only source.

Exclusionary terms is possible, i just haven't added it to the extension yet. I will add it to my to-do.

Checking if folder exists should be doable, or rather i could check if the folder that is about to be downloaded is already shared by the user?

Thanks for bringing these up and sorry again for the late response.

**Comment by peps1** [comment]
Excluding keywords from search has been added in: v1.0.0-beta.6

**Comment by peps1** [comment]
new in v1.0.0-beta.8

you can now exclude users
you can now skip dupes, either queue, share or both
items detected as dupes can also be removed from the search list

[full changelog](https://github.com/peps1/airdcpp-auto-downloader/blob/master/CHANGELOG.md#v100-beta8-2021-10-02)

**Comment by peps1** [comment]
As all of these should be working now, i'll close this issue. Please open a new issue if you encounter any problems or questions.
